### ISSUE TITLE
Not clear how to create new instances of apps

### ISSUE THREAD

**Issue by darconeous** [martinpaljak/GlobalPlatformPro#14]
It isn't entirely clear to me how to create a new instance of an installed applet using the `--create` argument. The relation of this argument with the `--package` and/or `--applet`/`--cap` arguments is also frustratingly vague.

I'm trying to create an instance of an OpenPGP app on a card with a specific serial number, but I can't seem to figure out the right arguments.

Doing something like `gp --package D27600012401 --applet D27600012401 --create 02000000000272950000` doesn't seem to work. (Error `Install for Install and make selectable failed SW: 6A88`)

Could you add some examples of how to do this?

**Comment by martinpaljak** [comment]
There is a bug in --cap option for --create in released version, fixed in HEAD. Specify the --packae and --applet as you get from the executable module for OpenPGP on card (gp -l tells you) and specify the new applet instance AID after --create

**Comment by darconeous** [comment]
Ok, so I'm not sure where I'm going wrong:

    $ gp -l
    AID: A000000003000000 (|........|)
         ISD OP_READY: Security Domain, Card lock, Card terminate, Default selected, CVM (PIN) management
    
    AID: A000000527210101 (|....'!..|)
         App SELECTABLE: (none)
    
    AID: D27600012401 (|.v..$.|)
         ExM LOADED: (none)
         D2760001240102000000000000000000 (|.v..$...........|)
    
    $ gp --package D27600012401 --applet D27600012401 --create D2760001240102000000000272950000
    pro.javacard.gp.GPException: Install for Install and make selectable failed SW: 6A88
    	at pro.javacard.gp.GlobalPlatform.check(GlobalPlatform.java:1039)
    	at pro.javacard.gp.GlobalPlatform.installAndMakeSelectable(GlobalPlatform.java:753)
    	at pro.javacard.gp.GPTool.main(GPTool.java:467)

I guess it isn't clear to me what the difference between `--package` and `--applet` is. Or even why I still see `D2760001240102000000000000000000` showing up under `ExM LOADED`, even though I deleted that instance.

Installing works great.

**Comment by darconeous** [comment]
AH-HAH! I figured out the secret sauce:

    gp --package D27600012401 --applet D2760001240102000000000000000000 --create D2760001240102000000000272950000

Might be a good example to add to the README, perhaps?

**Comment by darconeous** [comment]
And now I'm not sure how to make it the default selected. Gosh this thing makes me feel like an idiot. :P

    $ gp --package D27600012401 --applet D2760001240102000000000000000000 --make-default D2760001240102000000000272950000
    pro.javacard.gp.GPException: Install for make selectable failed SW: 6A86
    	at pro.javacard.gp.GlobalPlatform.check(GlobalPlatform.java:1039)
    	at pro.javacard.gp.GlobalPlatform.makeDefaultSelected(GlobalPlatform.java:777)
    	at pro.javacard.gp.GPTool.main(GPTool.java:541)

I've tried a few different combinations but nothing seems to do the trick. :/

**Comment by martinpaljak** [comment]
gp --package D27600012401 --applet D2760001240102000000000000000000 --create D2760001240102000000000272950000 --default


Yes, documentation requires updating, but some of the features that change the commands are not yet complete.

**Comment by martinpaljak** [comment]
Fixed by 73fd7ab157f6a72f039e4c83181535c36081fa2f I also describe the output of `--list` to make it more clear for newcomers.

**Comment by martinpaljak** [comment]
Also updated README about `-list` output. You deleted the instance but the package with the applet is still on the card. By default --install creates the instance with the default applet AID, as specified in CAP.

**Comment by martinpaljak** [comment]
Generally speaking, *some* knowledge of GlobalPlatform concepts and specification knowledge is required for successfully working with `gp` tool. It is definitely simpler than gpshell but such "glitches" from simple usage scenarios definitely mean that the README is not up to the task :) 

Thanks for reports and if you see anything else still missing from README, please open a specific ticket.

**Comment by darconeous** [comment]
Thanks!

Is it possible to mark an already created instance as the default after it had been created?

**Comment by darconeous** [comment]
And `$ gp --package D27600012401 --applet D2760001240102000000000000000000 --create D276000124010200FF00000272950000 --default` didn't seem to do the trick. It created the instance, but it still isn't default selected.

**Comment by martinpaljak** [comment]
Regarding making an applet default after installation: depends on card. What card are you using?

Please take the latest Git content where --create is fixed to honour the privileges during instance creation. I'll make a pre-release shortly.
